apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: replicas-patch.yaml
  - path: image-patch.yaml
  - path: resources-patch.yaml
  - path: configmap-prod.yaml
  - path: secret-prod.yaml

nameSuffix: -prod

commonLabels:
  environment: prod