apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap-prod.yaml   # ‚Üê AHORA ES RECURSO
  - secret-prod.yaml
  - hpa.yaml

patches:
  - path: replicas-patch.yaml
  - path: image-patch.yaml
  - path: resources-patch.yaml

nameSuffix: -prod

labels:
- pairs:
    environment: prod
